module.exports=(sequelize,DataTypes)=>{
    const CrmEntity=sequelize.define('CrmEntity',{
        crmid:{
            type:DataTypes.INTEGER(19),
        },
        smcreatorid:{
            type:DataTypes.INTEGER(19),
        },
        smownerid:{
            type:DataTypes.INTEGER(19),
        },
        modifiedby:{
            type:DataTypes.INTEGER(19),
        },
        setype:{
            type:DataTypes.STRING(30),
        },
        setype_id:{
            type:DataTypes.INTEGER(11),
            defaultValue:null,
        },
        description:{
            type:DataTypes.TEXT,
        },
        createdtime:{
            type:DataTypes.DATE,
        },
        modifiedtime:{
            type:DataTypes.DATE,
        },
        viewedtime:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        status:{
            type:DataTypes.STRING(50),
            defaultValue:null,
        },
        version:{
            type:DataTypes.INTEGER(19),
        },
        presence:{
            type:DataTypes.INTEGER(1),
            defaultValue:null,
        },
        deleted:{
            type:DataTypes.INTEGER(1),
        },
        sendstatus:{
            type:DataTypes.TINYINT(4),
            defaultValue:null,
        },
        terms_conditions:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
    },{
        tableName:'vtiger_crmentity',
        timestamps:false,
        freezeTableName:true,
    });
    CrmEntity.removeAttribute('id');
    return CrmEntity;
};