var RetailerCf=require('./retailer-cf');
module.exports=(sequelize,DataTypes)=>{
    const Retailer=sequelize.define('Retailer',{
        xretailerid:{
            type:DataTypes.INTEGER(11),
            autoIncrement:true,
            primaryKey: true,
        },
        customername:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        customercode:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        distributor_id:{
            type:DataTypes.BIGINT(20),
            defaultValue:null,
        },
        dob:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        doa:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        bank_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        branch_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        bank_account_number:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        ifsc_code:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        latitude:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        longitude:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        district:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        location_area:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        fssai:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        internal_ref_no:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        alternative_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        ret_store_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        cust_first_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        cust_middle_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        cust_last_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        gender:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        alternative_mob_num:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        district_code:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        area_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        taluka_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        street_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        market_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        typeshopfirm:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        idcardtype:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        id_card_number:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        idproofimagename:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        std_code:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        plot_number:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        landmark:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        lube_territory_code:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        lube_territory_name:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        retailerimagename:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        addressproof:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        unique_retailer_code:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        region:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        realignment_flag:{
            type:DataTypes.INTEGER(4),
            defaultValue:0,
        },
        mobile_application:{
            type:DataTypes.INTEGER(1),
            defaultValue:null,
        },
        customer_cd_key:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        created_at:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        modified_at:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        deleted:{
            type:DataTypes.INTEGER(1),
            defaultValue:0,
        },
        gstinno:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        panno:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        typeofservices:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        counter_sales_customer:{
            type:DataTypes.INTEGER(3),
            defaultValue:0,
        },
        xsupplychainhierid:{
            type:DataTypes.BIGINT(20),
            defaultValue:null,
        },
        retailer_type:{
            type:DataTypes.INTEGER(1),
            defaultValue:null,
        },
        posting_xdistributorid:{
            type:DataTypes.BIGINT(20),
            defaultValue:null,
        },
        retailer_program_flag4:{
            type:DataTypes.STRING(255),
        },
        retailer_program_flag3:{
            type:DataTypes.STRING(255),
        },
        retailer_program_flag2:{
            type:DataTypes.STRING(255),
        },
        retailer_program_flag1:{
            type:DataTypes.STRING(255),
            defaultValue:'No',
        },
        store_layout:{
            type:DataTypes.STRING(255),
        },
        store_type:{
            type:DataTypes.STRING(255),
        },
        store_size:{
            type:DataTypes.STRING(255),
        },
        shelves_count:{
            type:DataTypes.STRING(255),
        },
        retailer_drug_no_20b:{
            type:DataTypes.STRING(255),
            
        },
        retailer_drug_no_21b:{
            type:DataTypes.STRING(255),
            
        },
        generated_otp:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        is_otp_verified:{
            type:DataTypes.INTEGER(1),
            defaultValue:null,
        },
        branded_shop_board_presence:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        premium_edible_oil:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        branded_rice_presence:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        branded_soya_chunks:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        branded_atta_presence:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        branded_sugar:{
            type:DataTypes.ENUM('yes', 'no'),
            defaultValue:null,
        },
        helpers_count:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        population:{
            type:DataTypes.STRING(255),
            
        },
        helpers_count:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        village_type:{
            type:DataTypes.STRING(255),
            
        },
        pop_strata:{
            type:DataTypes.STRING(255),
            
        },
        retailertaxtype:{
            type:DataTypes.STRING(255),
            
        },
        isdruglicenserequired:{
            type:DataTypes.STRING(255),
            
        },
        retailer_program_flag5:{
            type:DataTypes.STRING(255),
        },
        retailer_program_flag6:{
            type:DataTypes.STRING(255),
        },
        sales_field_officer_code:{
            type:DataTypes.TEXT,
            defaultValue:null,
        },
        pincode_id:{
            type:DataTypes.BIGINT(20),
            defaultValue:null,
        },

    },{
        tableName:'vtiger_xretailer',
        timestamps:false,
        freezeTableName:true,
         indexes: [ { fields: [ 'distributor_id' ] },
         {fields:['customercode']},
         {fields:['unique_retailer_code']},
         {fields:['realignment_flag']} ],
    });
    /*Retailer.hasOne(sequelize.models.RetailerCf,{
        foreignKey:'xretailerid',
    });*/
    return Retailer;
};