module.exports=(sequelize,DataTypes)=>{
    const Salesman=sequelize.define('Salesman',{
        xsalesmanid:{
            type:DataTypes.INTEGER(11),
            primaryKey: true,
            defaultValue:0,
        },
        salesman:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        salesmancode:{
            type:DataTypes.STRING(255),
            defaultValue:null,
        },
        sman_mobile:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },

        sman_email:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        sman_password:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        sman_conf_password:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        classification:{
            type:DataTypes.STRING(100),
            defaultValue:null,
        },
        created_at:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        modified_at:{
            type:DataTypes.DATE,
            defaultValue:null,
        },
        deleted:{
            type:DataTypes.INTEGER(1),
            defaultValue:0,
        },
        counter_sales_beat:{
            type:DataTypes.INTEGER(3),
            defaultValue:0, 
        },
        profiletype:{
            type:DataTypes.STRING(50),
            defaultValue:null, 
        },
        salesman_program_flag1:{
            type:DataTypes.INTEGER(1),
            defaultValue:null, 
        },
        status:{
            type:DataTypes.STRING(25),
            defaultValue:null, 
        },
        next_stage_name:{
            type:DataTypes.STRING(50),
            defaultValue:null, 
        },
        unique_salesman_code:{
            type:DataTypes.STRING(50),
            defaultValue:null, 
        },
        xorganisationhierid:{
            type:DataTypes.INTEGER(11),
            defaultValue:null, 
        },
        user_reports_to_id:{
            type:DataTypes.INTEGER(11),
            defaultValue:null, 
        },
    },{
        tableName:'vtiger_xsalesman',
        timestamps:false,
        freezeTableName:true,
        indexes: [ { fields: [ 'salesmancode' ] }],
    });
    return Salesman;
};